'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {archiveDirectory,extractZip,createZip,MAX_ARCHIVE_BYTES,type ArchiveEntry} from '@/lib/tools/archive';
import {Preview} from './preview';
import {toolError} from '@/lib/tools/errors';
function DirectoryTree({entries,prefix='',render}:{entries:ArchiveEntry[];prefix?:string;render:(entry:ArchiveEntry)=>ReactNode}){const folders=new Map<string,ArchiveEntry[]>(),leaves:ArchiveEntry[]=[];for(const entry of entries){const rest=entry.name.slice(prefix.length),slash=rest.indexOf('/');if(slash>=0){const folder=rest.slice(0,slash+1);if(!folders.has(folder))folders.set(folder,[]);if(rest.length>slash+1)folders.get(folder)!.push(entry);}else leaves.push(entry);}return <>{[...folders].map(([folder,children])=><details key={folder} open><summary>{folder}</summary><DirectoryTree entries={children} prefix={prefix+folder} render={render}/></details>)}{leaves.map(render)}</>;}
export default function ArchiveInspector({file,language}:{file:File;language:'zh'|'en'}){
 const [manifest,setManifest]=useState<Record<string,{pages:number[];width:number;height:number}>>({}),[entries,setEntries]=useState<ArchiveEntry[]>([]),[selected,setSelected]=useState<string[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<{name:string;blob:Blob;text?:string}|null>(null);const t=(zh:string,en:string)=>language==='zh'?zh:en;
 useEffect(()=>{let active=true;setError('');setEntries([]);setPreview(null);setQuery('');void(async()=>{try{if(file.size>MAX_ARCHIVE_BYTES)throw new Error('Archive exceeds 64 MB');const bytes=new Uint8Array(await file.arrayBuffer());const directory=archiveDirectory(bytes);let imageInfo:Record<string,{pages:number[];width:number;height:number}>={};if(directory.some(entry=>entry.name==='images.json'&&entry.size<=128*1024)){try{const [part]=extractZip(bytes,['images.json']);const value=JSON.parse(await part.blob.text());if(Array.isArray(value))imageInfo=Object.fromEntries(value.filter(item=>typeof item.name==='string'&&Array.isArray(item.pages)).map(item=>[item.name,item]));}catch{}}if(active){setManifest(imageInfo);setEntries(directory);setSelected([]);}}catch(error){if(active)setError(toolError(error,language));}})();return()=>{active=false;};},[file,language]);
 const download=async()=>{setBusy(true);setError('');try{const files=extractZip(new Uint8Array(await file.arrayBuffer()),selected);const zip=await createZip(files,1,true);const url=URL.createObjectURL(zip),a=document.createElement('a');a.href=url;a.download='selected.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){setError(toolError(error,language));}finally{setBusy(false);}};
 const open=async(name:string)=>{setError('');try{const entry=entries.find(entry=>entry.name===name);if(!entry||entry.size>8*1024*1024)throw new Error(t('预览最多 8 MB，请下载查看。','Preview limit is 8 MB. Download to inspect.'));const [value]=extractZip(new Uint8Array(await file.arrayBuffer()),[name]);const ext=name.split('.').pop()?.toLowerCase()??'',mime=({png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',gif:'image/gif',mp3:'audio/mpeg',wav:'audio/wav',mp4:'video/mp4',pdf:'application/pdf'} as Record<string,string>)[ext]??'application/octet-stream';const blob=new Blob([value.blob],{type:mime});setPreview({name,blob,text:['txt','json','csv','yaml','yml','md'].includes(ext)?await blob.text():undefined});}catch(error){setError(toolError(error,language));}};
 const visible=entries.filter(entry=>entry.name.toLowerCase().includes(query.toLowerCase()));
 return <section>{error&&<p role="alert">{error}</p>}{entries.length>0&&<><p>{entries.length} {t('项','entries')} · {(entries.reduce((n,entry)=>n+entry.size,0)/1024/1024).toFixed(1)} MB {t('解压后','uncompressed')}</p><div className="archive-toolbar"><input aria-label={t('搜索压缩包文件','Search archive')} placeholder={t('搜索文件','Search files')} value={query} onChange={event=>setQuery(event.target.value)}/><button disabled={busy} onClick={()=>setSelected(visible.filter(entry=>!entry.name.endsWith('/')).map(entry=>entry.name))}>{t('全选当前列表','Select shown')}</button><button disabled={busy} onClick={()=>setSelected([])}>{t('取消选择','Clear selection')}</button><button disabled={busy||!selected.length} onClick={()=>void download()}>{t('下载所选 ZIP','Download selected as ZIP')}</button></div><div className="archive-entries"><DirectoryTree entries={visible} render={entry=><div key={entry.name} style={{paddingLeft:Math.min(6,entry.name.split('/').length-1)*12}}><label><input type="checkbox" disabled={busy||entry.name.endsWith('/')} checked={selected.includes(entry.name)} onChange={event=>setSelected(values=>event.target.checked?[...values,entry.name]:values.filter(name=>name!==entry.name))}/><span>{entry.name}</span><span>{entry.size} B{manifest[entry.name]&&<> · {manifest[entry.name].width} × {manifest[entry.name].height} px · {t('页面','Pages')} {manifest[entry.name].pages.join(', ')}</>}</span></label>{!entry.name.endsWith('/')&&<button onClick={()=>void open(entry.name)}>{t('预览','Preview')}</button>}</div>}/></div>{preview&&<div><h3>{preview.name}</h3>{preview.text?<pre>{preview.text}</pre>:<Preview blob={preview.blob} alt={preview.name}/>}</div>}</>}</section>;
}
