'use client';
import {useState,useEffect} from 'react';
import {parseCsv,parseJson,jsonToCsv,transformData} from '@/lib/tools/data';
import {toolError} from '@/lib/tools/errors';
function JsonNode({value,depth=0,budget={remaining:400}}:{value:unknown;depth?:number;budget?:{remaining:number}}){if(--budget.remaining<0)return null;if(value===null||typeof value!=='object')return <span>{JSON.stringify(value)}</span>;if(depth>=8)return <span>…</span>;return <details open={depth<1}><summary>{Array.isArray(value)?`[${value.length}]`:`{${Object.keys(value).length}}`}</summary>{Object.entries(value).slice(0,40).map(([key,item])=><div key={key} style={{paddingLeft:12}}><strong>{key}: </strong><JsonNode value={item} depth={depth+1} budget={budget}/></div>)}</details>;}
export default function DataInspector({toolId,settings,language,onLocate}:{toolId:string;settings:Record<string,unknown>;language:'zh'|'en';onLocate:(line:number,column:number)=>void}){const [data,setData]=useState<{rows?:string[][];json?:unknown;error?:string;line?:number;column?:number}|null>(null),t=(zh:string,en:string)=>language==='zh'?zh:en;
 useEffect(()=>setData(null),[settings.text,settings.columns,settings.flatten,settings.delimiter,settings.header]);
 const inspect=()=>{try{const text=String(settings.text??'');if(new TextEncoder().encode(text).length>8*1024*1024)throw new Error('Text input exceeds 8 MB.');if(toolId==='data.csv-json'){const delimiter=settings.delimiter==='tab'?'\t':String(settings.delimiter??',');setData({rows:parseCsv(text,delimiter).slice(0,31)});}else{const json=toolId==='data.yaml-json'?JSON.parse(transformData(toolId,text)):parseJson(text);setData(toolId==='data.json-csv'?{rows:parseCsv(jsonToCsv(json,String(settings.columns??''),Boolean(settings.flatten))).slice(0,31)}:{json});}}catch(error){const match=String(error).match(/JSON: (\d+):(\d+)/);setData({error:toolError(error,language),line:match?Number(match[1]):undefined,column:match?Number(match[2]):undefined});}};
 return <section className="data-inspector"><button onClick={inspect}>{t('检查输入结构','Inspect input structure')}</button>{data?.error&&<p role="alert">{data.error}{data.line&&<button onClick={()=>onLocate(data.line!,data.column!)}>{t('定位错误','Locate error')}</button>}</p>}{data?.rows&&<><p>{t('前 30 行；完整数据以导出结果为准。','First 30 rows. Export contains the full data.')}</p><div className="data-grid"><table><tbody>{data.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=>i===0&&settings.header!==false?<th key={j}>{cell}</th>:<td key={j}>{cell}</td>)}</tr>)}</tbody></table></div></>}{data&&'json' in data&&<div className="json-tree"><JsonNode value={data.json}/></div>}</section>;
}
