'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {listHistory,clearHistory,type HistoryEntry} from '@/lib/history';
import {tasks,forgetTask,type SavedTask} from '@/lib/tools/workbench-state';
import {getTool,toolPath} from '@/lib/tools/registry';
import {useInterface} from '@/lib/use-interface';
import {safeSettings} from '@/lib/tools/presets';
import WorkbenchShell from './workbench-shell';
export default function HistoryWorkbench(){const ui=useInterface(),[entries,setEntries]=useState<HistoryEntry[]>([]),[saved,setSaved]=useState<SavedTask[]>([]),[status,setStatus]=useState<Record<string,string>>({});const t=(zh:string,en:string)=>ui.language==='zh'?zh:en;
 useEffect(()=>{void listHistory().then(setEntries);const list=tasks();setSaved(list);void Promise.allSettled(list.map(async task=>{const response=await fetch(`/api/jobs/${task.id}`);const data=await response.json();setStatus(old=>({...old,[task.id]:response.ok?data.status:'EXPIRED'}));}));},[]);
 return <WorkbenchShell {...ui} onLanguage={()=>ui.setLanguage(ui.language==='zh'?'en':'zh')} onTheme={ui.setTheme}><main className="history-workbench glass"><h1>{t('历史记录','History')}</h1><p>{t('复用设置需要重新选择文件；服务器结果到期后会删除。','Choose files again when reusing settings. Server results expire automatically.')}</p>{saved.length>0&&<section><h2>{t('服务器任务与结果','Server jobs and results')}</h2>{saved.map(task=>{const tool=getTool(task.toolId);return <div className="task-row" key={task.id}><span>{tool?.name[ui.language]} · {task.name}<small> · {({COMPLETED:t('已完成','Completed'),PROCESSING:t('处理中','Processing'),QUEUED:t('排队中','Queued'),FAILED:t('失败','Failed'),CANCELLED:t('已取消','Cancelled'),EXPIRED:t('已过期','Expired')} as Record<string,string>)[status[task.id]]??t('检查中','Checking')}</small></span>{status[task.id]==='COMPLETED'&&<a href={`/api/jobs/${task.id}/download`}>{t('下载','Download')}</a>}{tool&&['PROCESSING','QUEUED'].includes(status[task.id])&&<Link href={`${toolPath(tool)}?resume=${task.id}`}>{t('恢复查看','Resume')}</Link>}{tool&&['FAILED','CANCELLED'].includes(status[task.id])&&<Link href={toolPath(tool)} onClick={()=>sessionStorage.setItem('convertbox-replay',JSON.stringify({toolId:tool.id,settings:safeSettings(task.settings)}))}>{t('复用设置重试','Reuse settings to retry')}</Link>}{status[task.id]==='EXPIRED'&&<button onClick={()=>{forgetTask(task.id);setSaved(tasks());}}>{t('移除失效记录','Remove expired entry')}</button>}</div>;})}</section>}
 <section><div className="history-heading"><h2>{t('处理记录','Processed files')}</h2>{entries.length>0&&<button onClick={()=>{void clearHistory().then(()=>setEntries([]));}}>{t('清空记录','Clear history')}</button>}</div>{entries.map(entry=>{const tool=getTool(entry.toolId??'');return <div className="task-row" key={entry.id}><span><strong>{tool?.name[ui.language]??entry.name}</strong><br/>{entry.name} · {({COMPLETED:t('已完成','Completed'),PARTIAL:t('部分完成','Partially completed'),FAILED:t('失败','Failed'),CANCELLED:t('已取消','Cancelled')} as Record<string,string>)[entry.status??'COMPLETED']} · {entry.outputFormat.toUpperCase()} · {new Date(entry.createdAt).toLocaleString(ui.language==='zh'?'zh-CN':'en-US')}</span>{tool&&<Link href={toolPath(tool)} onClick={()=>sessionStorage.setItem('convertbox-replay',JSON.stringify({toolId:tool.id,settings:safeSettings(entry.settings)}))}>{t('复用设置','Reuse settings')}</Link>}</div>;})}{!entries.length&&<p>{t('暂无记录','No history yet')}</p>}</section></main></WorkbenchShell>;
}
