/* eslint-disable @next/next/no-img-element */
'use client';
import {useEffect,useRef,useState} from 'react';
import {useBlobUrl} from './preview';
import {previewJob,previewReport} from '@/lib/tools/preview-jobs';
import {deleteServerJob} from '@/lib/server-api';
import {toolError} from '@/lib/tools/errors';
export const seconds=(value:unknown)=>String(value??0).split(':').reduce((n,p)=>n*60+Number(p),0);
export const timestamp=(value:number)=>Number.isFinite(value)?value.toFixed(3):'0.000';
interface Props {file:File;toolId:string;settings:Record<string,unknown>;onChange:(settings:Record<string,unknown>)=>void;language:'zh'|'en';disabled?:boolean}
export default function MediaEditor({file,toolId,settings,onChange,language,disabled=false}:Props){
 const original=useBlobUrl(file),[proxy,setProxy]=useState(''),[length,setLength]=useState(0),[time,setTime]=useState(0),[peaks,setPeaks]=useState<number[]>([]),[zoom,setZoom]=useState(1),[offset,setOffset]=useState(0),[loop,setLoop]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState(''),[info,setInfo]=useState<{tracks:Record<string,unknown>[]}|null>(null),[analysis,setAnalysis]=useState<Record<string,string>|null>(null),[frames,setFrames]=useState<string[]>([]),[gif,setGif]=useState<{url:string;size:number}|null>(null);
 const media=useRef<HTMLMediaElement|null>(null),request=useRef<AbortController|null>(null),proxyId=useRef(''),gifId=useRef(''),captureId=useRef(0),initial=useRef(false);
 const t=(zh:string,en:string)=>language==='zh'?zh:en,video=toolId.startsWith('video.')&&toolId!=='video.extract-audio';
 const start=Math.max(0,seconds(settings.start)),end=toolId==='video.gif'?Math.min(length,start+Number(settings.duration??5)):Math.min(length,seconds(settings.end??length));
 const selecting=toolId.endsWith('.trim')||toolId==='video.gif',span=length/zoom,from=offset*(length-span),to=from+span;
 useEffect(()=>{initial.current=false;captureId.current++;setLength(0);setTime(0);setPeaks([]);setFrames([]);setGif(null);setProxy('');setInfo(null);setError('');setAnalysis(null);setZoom(1);setOffset(0);return()=>{
 // This is a generation counter, not a DOM ref.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 captureId.current++;request.current?.abort();if(proxyId.current)void deleteServerJob(proxyId.current).catch(()=>{});if(gifId.current)void deleteServerJob(gifId.current).catch(()=>{});};},[file]);
 useEffect(()=>{setGif(null);},[settings.start,settings.duration,settings.width,settings.fps,settings.quality]);
 const metadata=()=>{const element=media.current;if(!element||!Number.isFinite(element.duration))return;setLength(element.duration);onChange({media_duration:element.duration});if(!initial.current){initial.current=true;if(toolId.endsWith('.trim')&&String(settings.end)==='00:00:10')onChange({end:timestamp(element.duration)});if(toolId==='video.gif')onChange({duration:Math.min(5,element.duration)});}};
 const seek=(at:number)=>{if(!media.current)return;media.current.currentTime=Math.max(0,Math.min(length,at));setTime(at);};
 const analyze=async(mode:'waveform'|'info'|'proxy'|'loudness')=>{setPending(true);setError('');const controller=new AbortController();request.current=controller;try{
  if(mode==='proxy'){const job=await previewJob(file,'audio.preview','mp3',{audio_track:Number(settings.audio_track??0)},controller.signal);if(proxyId.current)void deleteServerJob(proxyId.current).catch(()=>{});proxyId.current=job.id;setProxy(job.url);}
  else if(mode==='waveform'){const data=await previewReport<{duration:number;peaks:number[]}>(file,'audio.waveform',{audio_track:Number(settings.audio_track??0)},controller.signal);setLength(data.duration);setPeaks(data.peaks);}
  else if(mode==='info'){const data=await previewReport<{duration:number;tracks:Record<string,unknown>[]}>(file,'media.info',{},controller.signal);setInfo(data);setLength(data.duration);}
  else setAnalysis(await previewReport(file,'audio.analyze',{audio_track:Number(settings.audio_track??0)},controller.signal));
 }catch(error){if(!controller.signal.aborted)setError(toolError(error,language));}finally{setPending(false);}};
 const gifPreview=async()=>{setPending(true);setError('');const controller=new AbortController();request.current=controller;try{const job=await previewJob(file,'video.gif','gif',{start:String(settings.start??'0'),duration:Number(settings.duration??5),width:Math.min(240,Number(settings.width??480)),fps:Math.min(10,Number(settings.fps??12)),quality:'light'},controller.signal);if(gifId.current)void deleteServerJob(gifId.current).catch(()=>{});gifId.current=job.id;setGif({url:job.url,size:job.size});}catch(error){if(!controller.signal.aborted)setError(toolError(error,language));}finally{setPending(false);}};
 const thumbnails=async()=>{
  const element=media.current as HTMLVideoElement|null;if(!element||!length)return;const token=++captureId.current;element.pause();setLoop(false);setPending(true);setError('');const old=element.currentTime;const canvas=document.createElement('canvas');const scale=Math.min(160/(element.videoWidth||160),100/(element.videoHeight||90));canvas.width=Math.max(2,Math.round((element.videoWidth||160)*scale));canvas.height=Math.max(2,Math.round((element.videoHeight||90)*scale));const values:string[]=[];
  try{for(let i=0;i<8;i++){if(captureId.current!==token)break;await new Promise<void>((resolve,reject)=>{const timeout=window.setTimeout(()=>{element.removeEventListener('seeked',done);reject(new Error('Video frame preview timed out'));},4000);const done=()=>{clearTimeout(timeout);element.removeEventListener('seeked',done);resolve();};element.addEventListener('seeked',done);element.currentTime=Math.min(length-.01,length*(i+.5)/8);});canvas.getContext('2d')?.drawImage(element,0,0,canvas.width,canvas.height);values.push(canvas.toDataURL('image/jpeg',.6));}if(captureId.current===token){setFrames(values);element.currentTime=old;}}catch(error){setError(toolError(error,language));}finally{canvas.width=canvas.height=0;setPending(false);}
 };
 const tick=()=>{const at=media.current?.currentTime??0;setTime(at);if(selecting&&loop&&end>start&&at>=end){seek(start);void media.current?.play().catch(()=>{});}};
 const videoTrack=info?.tracks.find(track=>track.codec_type==='video'),fpsParts=String(videoTrack?.r_frame_rate??'30/1').split('/').map(Number),frameRate=fpsParts[0]/(fpsParts[1]||1)||30;
 const frameTimes=toolId==='video.frames'&&length?settings.mode==='single'?[seconds(settings.start)]:settings.mode==='interval'?Array.from({length:Math.min(100,Math.ceil(length/Number(settings.interval??5)))},(_,i)=>i*Number(settings.interval??5)):Array.from({length:Number(settings.count??10)},(_,i)=>length*(i+.5)/Number(settings.count??10)):[];
 const audioTracks=info?.tracks.filter(track=>track.codec_type==='audio')??[];
 const changeStart=(at:number)=>{const value=Math.max(0,Math.min(length-.01,at));onChange({start:timestamp(value),...(toolId==='video.gif'?{duration:Math.min(Number(settings.duration??5),length-value)}:{end:timestamp(Math.min(length,Math.max(value+.01,end)))})});seek(value);};
 return <section className="media-editor"><div className="media-player">{video?<video ref={element=>{media.current=element;}} src={original} controls preload="metadata" onLoadedMetadata={metadata} onTimeUpdate={tick} onError={()=>setError(t('浏览器无法播放此格式，可转换后预览或生成试听文件。','This format cannot play here. Convert it or create an audio preview.'))}/>:<audio ref={element=>{media.current=element;}} src={proxy||original} controls preload="metadata" onLoadedMetadata={metadata} onTimeUpdate={tick} onError={()=>setError(t('浏览器无法播放此格式，请生成试听文件。','Create a preview to play this format.'))}/>}</div>{video&&proxy&&<audio controls src={proxy} preload="metadata"/>}
 <p>{t('时长','Duration')} {timestamp(length)} s · {t('当前位置','Position')} {timestamp(time)} s {selecting&&<> · {t('所选','Selected')} {timestamp(Math.max(0,end-start))} s</>}</p>
 <fieldset disabled={disabled||pending} className="media-toolbar"><button onClick={()=>void analyze('info')}>{t('读取轨道','Read tracks')}</button>{!video&&<button onClick={()=>void analyze('waveform')}>{t('生成波形','Generate waveform')}</button>}<button onClick={()=>void analyze('proxy')}>{t('生成试听文件','Create audio preview')}</button>{toolId==='audio.normalize'&&<button onClick={()=>void analyze('loudness')}>{t('测量响度','Measure loudness')}</button>}{toolId==='video.gif'&&<button onClick={()=>void gifPreview()}>{t('生成轻量 GIF 预览','Generate lightweight GIF preview')}</button>}{video&&<button onClick={()=>void thumbnails()}>{t('生成时间轴缩略图','Build timeline thumbnails')}</button>}</fieldset>
 {gif&&<div><p>{(gif.size/1024).toFixed(1)} KB · {t('低分辨率预览，最终导出使用右侧参数。','Low resolution preview. Export uses the settings on the right.')}</p><img className="result-preview" src={gif.url} alt={t('GIF 片段预览','GIF clip preview')}/></div>}
 {pending&&<p role="status">{t('正在生成预览，可取消','Generating preview')} <button onClick={()=>{captureId.current++;request.current?.abort();setPending(false);}}>{t('取消','Cancel')}</button></p>}{error&&<p role="alert">{error}</p>}
 {!!length&&<><div className="media-wave" role="slider" aria-label={t('时间轴','Timeline')} aria-valuemin={0} aria-valuemax={length} aria-valuenow={time} tabIndex={0} onKeyDown={event=>{if(event.key==='ArrowRight')seek(time+.1);if(event.key==='ArrowLeft')seek(time-.1);}} onClick={event=>{const rect=event.currentTarget.getBoundingClientRect();seek(from+(event.clientX-rect.left)/rect.width*span);}}>
 <svg viewBox="0 0 1000 130" preserveAspectRatio="none" aria-hidden="true"><rect x={Math.max(0,(start-from)/span*1000)} y="0" width={selecting?Math.max(0,(end-start)/span*1000):0} height="130" fill="#3478f6" opacity=".12"/>{peaks.length>0?peaks.map((peak,index)=>{const at=index/peaks.length*length;if(at<from||at>to)return null;return <line key={index} x1={(at-from)/span*1000} x2={(at-from)/span*1000} y1={65-peak*60} y2={65+peak*60} stroke="#4f85d7" strokeWidth="1.5"/>;}):<line x1="0" x2="1000" y1="65" y2="65" stroke="#94a3b8"/>}<line x1={(time-from)/span*1000} x2={(time-from)/span*1000} y1="0" y2="130" stroke="#e58949" strokeWidth="2"/></svg>{selecting&&<><input className="wave-handle wave-start" aria-label={t('波形起点手柄','Waveform start handle')} type="range" min={from} max={to} step=".01" value={Math.max(from,Math.min(to,start))} disabled={disabled} style={{visibility:start<from||start>to?'hidden':'visible'}} onChange={event=>changeStart(Number(event.target.value))}/><input className="wave-handle wave-end" aria-label={t('波形终点手柄','Waveform end handle')} type="range" min={from} max={to} step=".01" value={Math.max(from,Math.min(to,end))} disabled={disabled} style={{visibility:end<from||end>to?'hidden':'visible'}} onChange={event=>{const value=Math.max(start+.01,Number(event.target.value));onChange(toolId==='video.gif'?{duration:Math.min(15,value-start)}:{end:timestamp(value)});}}/></>}
 </div>{frames.length>0&&<div className="video-thumbnails">{frames.map((src,i)=><button key={i} onClick={()=>seek(length*(i+.5)/frames.length)}><img src={src} alt={`${timestamp(length*(i+.5)/frames.length)} s`}/></button>)}</div>}
 <details className="timeline-options"><summary>{t('时间轴选项','Timeline options')}</summary><div className="tool-settings"><label>{t('定位','Seek')}<input aria-label={t('定位','Seek')} type="range" min="0" max={length} step=".01" value={time} onChange={event=>seek(Number(event.target.value))}/></label><label>{t('时间轴缩放','Timeline zoom')}<input type="range" min="1" max="32" value={zoom} onChange={event=>setZoom(Number(event.target.value))}/></label>{zoom>1&&<label>{t('时间轴位置','Timeline position')}<input type="range" min="0" max="1" step=".01" value={offset} onChange={event=>setOffset(Number(event.target.value))}/></label>}</div></details>
 {selecting&&<fieldset disabled={disabled} className="tool-settings"><button onClick={()=>{seek(start);setLoop(true);void media.current?.play().catch(()=>{});}}>{t('循环试听选区','Loop selection')}</button><button onClick={()=>setLoop(false)}>{t('停止循环','Stop loop')}</button>{video&&<><button onClick={()=>seek(time-1/frameRate)}>{t(`前移 1/${frameRate.toFixed(0)} 秒`,`Back 1/${frameRate.toFixed(0)} second`)}</button><button onClick={()=>seek(time+1/frameRate)}>{t(`后移 1/${frameRate.toFixed(0)} 秒`,`Forward 1/${frameRate.toFixed(0)} second`)}</button></>}</fieldset>}
 {toolId==='video.frames'&&settings.mode==='single'&&<button disabled={disabled} onClick={()=>onChange({start:timestamp(time)})}>{t('使用当前画面','Use current frame')}</button>}</>}
 {frameTimes.length>0&&<div className="frame-times"><p>{t('采样位置','Sample times')} · {frameTimes.length} {t('帧','frames')}</p>{frameTimes.map((at,i)=><button key={i} onClick={()=>seek(at)}>{at.toFixed(2)} s</button>)}</div>}
 {audioTracks.length>0&&<label>{t('音轨','Audio track')}<select disabled={disabled} value={String(settings.audio_track??0)} onChange={event=>{setPeaks([]);onChange({audio_track:Number(event.target.value)});}}>{audioTracks.map((track,i)=><option key={i} value={i}>{i+1} · {String((track.tags as {language?:string}|undefined)?.language??'')} · {String(track.codec_name)} · {String(track.channels??'')} {t('声道','channels')}</option>)}</select></label>}
 {analysis&&<dl className="tool-report">{Object.entries(analysis).map(([name,value])=><div key={name}><dt>{({integrated_lufs:t('综合响度（LUFS）','Integrated loudness (LUFS)'),true_peak_dbtp:t('真峰值（dBTP）','True peak (dBTP)'),loudness_range_lu:t('响度范围（LU）','Loudness range (LU)')} as Record<string,string>)[name]}</dt><dd>{value}</dd></div>)}</dl>}
 </section>;
}
