'use client';
import {useRef,useState,useEffect} from 'react';
import {previewReport} from '@/lib/tools/preview-jobs';
import {toolError} from '@/lib/tools/errors';
export default function MetadataCheck({source,result,language}:{source:File;result:File;language:'zh'|'en'}){const [data,setData]=useState<Record<string,unknown>[]|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),request=useRef<AbortController|null>(null),t=(zh:string,en:string)=>language==='zh'?zh:en;
 useEffect(()=>()=>request.current?.abort(),[]);
 const check=async()=>{const controller=new AbortController();request.current=controller;setBusy(true);setError('');try{const before=await previewReport<Record<string,unknown>>(source,source.name.toLowerCase().endsWith('.pdf')?'pdf.metadata':'image.metadata',{},controller.signal);const after=await previewReport<Record<string,unknown>>(result,result.name.toLowerCase().endsWith('.pdf')?'pdf.metadata':'image.metadata',{},controller.signal);setData([before,after]);}catch(error){if(!controller.signal.aborted)setError(toolError(error,language));}finally{setBusy(false);}};
 return <section><button disabled={busy} onClick={()=>void check()}>{busy?t('核对中','Checking'):t('核对元数据移除结果','Verify removed metadata')}</button>{error&&<p role="alert">{error}</p>}{data&&<table><thead><tr><th>{t('项目','Field')}</th><th>{t('原文件','Source')}</th><th>{t('结果','Result')}</th></tr></thead><tbody>{(source.name.toLowerCase().endsWith('.pdf')?[['title',t('标题','Title')],['author',t('作者','Author')],['subject',t('主题','Subject')],['keywords',t('关键词','Keywords')],['encrypted',t('加密','Encrypted')]]:[['exif',t('拍摄信息','Camera tags')],['gps',t('位置','Location')],['icc_bytes',t('色彩配置','Color profile')]]).map(([key,label])=><tr key={key}><td>{label}</td>{data.map((values,i)=><td key={i}>{values[key]?typeof values[key]==='object'?Object.keys(values[key] as object).length:typeof values[key]==='string'?String(values[key]):t('有','Present'):t('无','None')}</td>)}</tr>)}</tbody></table>}</section>;
}
