/* eslint-disable @next/next/no-img-element */
'use client';
import {useEffect,useRef,useState} from 'react';
import {previewReport} from '@/lib/tools/preview-jobs';
import {toolError} from '@/lib/tools/errors';
interface Page {page:number;thumbnail:string;rotation:number;selected:boolean;width:number;height:number}
export default function PdfOrganizer({file,onChange,language,mode,settings={},disabled=false}:{file:File;onChange:(values:Record<string,unknown>)=>void;language:'zh'|'en';mode:string;settings?:Record<string,unknown>;disabled?:boolean}){
 const [pages,setPages]=useState<Page[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[undo,setUndo]=useState<Page[][]>([]),[offset,setOffset]=useState(0);const drag=useRef(-1),latest=useRef(settings),init=useRef(false);latest.current=settings;
 const t=(zh:string,en:string)=>language==='zh'?zh:en,organize=mode==='pdf.organize';
 useEffect(()=>{const controller=new AbortController();init.current=false;setPages([]);setLoading(true);setError('');setUndo([]);setOffset(0);void previewReport<{pages:Page[]}>(file,'pdf.preview',{},controller.signal).then(data=>{const order=latest.current.page_order?JSON.parse(String(latest.current.page_order)) as {page:number;rotation:number}[]:null;const list=data.pages.map(page=>({...page,rotation:0,selected:false}));const restored=organize&&order?.length?order.map(item=>({...list[item.page],rotation:item.rotation})):list;setPages(restored);onChange({pdf_page_count:data.pages.length});init.current=true;if(organize&&!order?.length)onChange({page_order:JSON.stringify(list.map(page=>({page:page.page,rotation:0})))});}).catch(error=>{if(!controller.signal.aborted)setError(toolError(error,language));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[file,mode,onChange,organize,language]);
 const changed=(values:Page[])=>{setUndo(old=>[...old.slice(-9),pages]);setPages(values);onChange(organize?{page_order:JSON.stringify(values.map(({page,rotation})=>({page,rotation})))}:{pages:values.filter(page=>page.selected).map(page=>page.page+1).join(',')||'none'});};
 const selected=(page:Page)=>{if(organize)return page.selected;const spec=String(settings.pages??'none');if(spec==='all')return true;return spec.split(',').some(part=>{const [first,last]=part.split('-').map(Number);return page.page+1>=first&&page.page+1<=(last||first);});};
 const select=(index:number,value:boolean)=>changed(pages.map((page,at)=>({...page,selected:at===index?value:selected(page)})));
 const count=pages.filter(selected).length;
 return <section>{loading&&<p>{t('正在生成页面预览','Generating page previews')}</p>}{error&&<p role="alert">{error}</p>}{pages.length>0&&<><p>{pages.length} {t('页','pages')} · {t(mode==='pdf.delete-pages'?'将删除':mode==='pdf.extract-pages'?'将提取':'已选择',mode==='pdf.delete-pages'?'To delete':mode==='pdf.extract-pages'?'To extract':'Selected')} {count}</p><fieldset disabled={disabled||loading} className="tool-settings"><button onClick={()=>changed(pages.map(page=>({...page,selected:true})))}>{t('全选','Select all')}</button><button onClick={()=>changed(pages.map(page=>({...page,selected:false})))}>{t('取消选择','Clear selection')}</button>{organize&&<><button disabled={!count} onClick={()=>changed(pages.map(page=>selected(page)?{...page,rotation:(page.rotation+90)%360}:page))}>{t('旋转所选','Rotate selected')}</button><button disabled={!count||count===pages.length} onClick={()=>changed(pages.filter(page=>!selected(page)))}>{t('删除所选','Delete selected')}</button></>}<button disabled={!undo.length} onClick={()=>{const previous=undo[undo.length-1];setPages(previous);setUndo(values=>values.slice(0,-1));onChange(organize?{page_order:JSON.stringify(previous.map(({page,rotation})=>({page,rotation})))}:{pages:previous.filter(page=>page.selected).map(page=>page.page+1).join(',')||'none'});}}>{t('撤销','Undo')}</button></fieldset><div className="pdf-page-grid">{pages.slice(offset,offset+12).map((page,relative)=>{const index=offset+relative;return <div key={page.page} draggable={organize&&!disabled} onDragStart={()=>drag.current=index} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();if(disabled)return;const copy=[...pages];if(drag.current>=0){const [moved]=copy.splice(drag.current,1);copy.splice(index,0,moved);changed(copy);}drag.current=-1;}}><label><input disabled={disabled} type="checkbox" checked={selected(page)} onChange={event=>select(index,event.target.checked)}/>{t('原页面','Source page')} {page.page+1}</label><img src={page.thumbnail} alt={`${t('页面','Page')} ${page.page+1}`} style={{transform:`rotate(${page.rotation+(mode==='pdf.rotate'&&selected(page)?Number(settings.rotation??90):0)}deg)`}}/>{organize&&<div><button disabled={disabled||index===0} aria-label={t('前移页面','Move page earlier')} onClick={()=>{const copy=[...pages];[copy[index-1],copy[index]]=[copy[index],copy[index-1]];changed(copy);}}>←</button><button disabled={disabled||index===pages.length-1} aria-label={t('后移页面','Move page later')} onClick={()=>{const copy=[...pages];[copy[index+1],copy[index]]=[copy[index],copy[index+1]];changed(copy);}}>→</button></div>}</div>;})}</div>{pages.length>12&&<div className="tool-result-actions"><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-12))}>←</button><span>{Math.floor(offset/12)+1} / {Math.ceil(pages.length/12)}</span><button disabled={offset+12>=pages.length} onClick={()=>setOffset(offset+12)}>→</button></div>}</>}</section>;
}
