/* eslint-disable @next/next/no-img-element */
'use client';
import {useEffect,useRef,useState} from 'react';
import {previewReport} from '@/lib/tools/preview-jobs';
import {toolError} from '@/lib/tools/errors';
interface Page {thumbnail:string;width:number;height:number;page:number}
export default function PdfPreview({file,settings,toolId,onChange,language,disabled}:{file:File;settings:Record<string,unknown>;toolId:string;onChange:(s:Record<string,unknown>)=>void;language:'zh'|'en';disabled:boolean}){
 const [page,setPage]=useState(1),[data,setData]=useState<{pages:Page[];total:number;selectable_text:boolean}|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[proof,setProof]=useState('');const proofController=useRef<AbortController|null>(null);const dragging=useRef(false),t=(zh:string,en:string)=>language==='zh'?zh:en;
 useEffect(()=>{setLoading(true);setError('');const controller=new AbortController();void previewReport<typeof data>(file,'pdf.preview',{page},controller.signal).then(value=>{setData(value);if(value)onChange({pdf_page_count:value.total});}).catch(error=>{if(!controller.signal.aborted)setError(toolError(error,language));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[file,page,language,onChange]);
 useEffect(()=>{setProof('');return()=>proofController.current?.abort();},[settings,page,file]);
 const renderProof=async()=>{setLoading(true);setError('');const controller=new AbortController();proofController.current=controller;try{const values=Object.fromEntries(Object.entries(settings).filter(([,value])=>['string','number','boolean'].includes(typeof value))) as Record<string,string|number|boolean>;const result=await previewReport<{pages:Page[]}>(file,'pdf.proof',{...values,page,source_operation:toolId},controller.signal);setProof(result.pages[0].thumbnail);}catch(error){setError(toolError(error,language));}finally{setLoading(false);}};
 const value=data?.pages[0],position=String(settings.position??'center'),watermark=toolId==='pdf.watermark',numbering=toolId==='pdf.page-numbers';
 const x=Number(settings.x_percent??(position.endsWith('left')?8:position.endsWith('right')?80:50)),y=Number(settings.y_percent??(position.startsWith('top')?10:position.startsWith('bottom')?92:50));
 const overlay=watermark?String(settings.text??''):numbering?String(settings.format??'{n} / {total}').replace('{n}',String(Number(settings.start??1)+page-1)).replace('{total}',String(data?.total??0)):'';
 return <section>{loading&&<p role="status">{t('正在加载页面','Loading page')}</p>}{error&&<p role="alert">{error}</p>}{value&&<><div className="pdf-proof" onPointerMove={event=>{if(!dragging.current||disabled)return;const rect=event.currentTarget.getBoundingClientRect();onChange({x_percent:Math.max(0,Math.min(95,(event.clientX-rect.left)/rect.width*100)),y_percent:Math.max(5,Math.min(95,(event.clientY-rect.top)/rect.height*100))});}} onPointerUp={()=>dragging.current=false} onPointerCancel={()=>dragging.current=false}><img src={value.thumbnail} alt={`${t('页面','Page')} ${page}`}/>{overlay&&<span className="pdf-overlay" style={{left:`${watermark?x:position.endsWith('left')?8:position.endsWith('right')?85:50}%`,top:`${watermark?y:position.startsWith('top')?8:92}%`,fontSize:`${Number(settings.font_size??36)/value.width*100}cqw`,opacity:watermark?Number(settings.opacity??.2):1,transform:`translate(-50%,-50%) rotate(${watermark?-Number(settings.rotation??45):0}deg)`}} onPointerDown={event=>{if(!watermark||disabled)return;event.currentTarget.setPointerCapture(event.pointerId);dragging.current=true;}}>{overlay}</span>}</div><div className="tool-settings"><button disabled={page<=1} onClick={()=>setPage(page-1)}>←</button><label>{t('预览页','Preview page')}<input type="number" min="1" max={data?.total??1} value={page} onChange={event=>setPage(Math.max(1,Math.min(data?.total??1,Number(event.target.value)||1)))}/></label><span>/ {data?.total}</span><button disabled={page>=(data?.total??1)} onClick={()=>setPage(page+1)}>→</button></div>{(watermark||numbering)&&<><button disabled={disabled||loading} onClick={()=>void renderProof()}>{t('检查实际渲染','Check rendered preview')}</button>{proof&&<img className="result-preview" src={proof} alt={t('实际渲染预览','Rendered preview')}/>}<p>{t('位置示意；导出后可检查实际 PDF。','Placement guide; inspect the exported PDF for the final rendering.')}</p></>}{toolId==='pdf.convert'&&<p>{data?.selectable_text?t('检测到可选文字；Word 输出提取文字，不保留原排版。','Selectable text found. Word export extracts text without preserving the original layout.'):t('未检测到可选文字，请使用扫描 PDF 识别。','No selectable text detected. Use scanned PDF recognition.')}</p>}{toolId==='pdf.split'&&<div className="pdf-split-groups">{(String(settings.pages??'all')==='all'?Array.from({length:data?.total??0},(_,i)=>String(i+1)):String(settings.pages).split(';')).map((group,i)=><span key={i}>{t('文件','File')} {i+1}: {group}</span>)}</div>}{toolId==='pdf.convert'&&['png','jpg'].includes(String(settings.output))&&<p>{t('输出尺寸','Output dimensions')} {Math.round(value.width*Number(settings.dpi??144)/72)} × {Math.round(value.height*Number(settings.dpi??144)/72)} px</p>}</>}</section>;
}
