/* eslint-disable @next/next/no-img-element -- thumbnails are local validated raster data */
'use client';
import {useEffect,useRef,useState} from 'react';
import {createServerJob,pollServerJob,deleteServerJob} from '@/lib/server-api';
interface Page {page:number;thumbnail:string;rotation:number;selected:boolean}
export default function PdfOrganizer({file,onChange,language,mode}: {file:File;onChange:(values:Record<string,unknown>)=>void;language:'zh'|'en';mode:string}) {
  const [pages,setPages]=useState<Page[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);const drag=useRef(-1);
  const t=(zh:string,en:string)=>language==='zh'?zh:en;
  useEffect(()=>{const controller=new AbortController();let id='';setPages([]);setLoading(true);setError('');void(async()=>{try{const job=await createServerJob([file],'json','pdf.preview',{},controller.signal,'pdf.preview');id=job.id;const done=await pollServerJob(id,()=>{},controller.signal);if(done.status!=='COMPLETED')throw new Error(done.error??'Preview failed');const response=await fetch(`/api/jobs/${id}/download`,{signal:controller.signal});if(!response.ok||Number(response.headers.get('content-length'))>16*1024*1024)throw new Error('Preview too large');const data=await response.json() as {pages:Page[]};setPages(data.pages.map(page=>({...page,rotation:0,selected:mode==='pdf.organize'})));}catch(error){if(!controller.signal.aborted)setError(error instanceof Error?error.message:String(error));}finally{if(!controller.signal.aborted)setLoading(false);if(id)void deleteServerJob(id).catch(()=>{});}})();return()=>{controller.abort();if(id)void deleteServerJob(id).catch(()=>{});};},[file,mode]);
  useEffect(()=>{onChange(mode==='pdf.organize'?{page_order:JSON.stringify(pages.map(({page,rotation})=>({page,rotation})))}:{pages:pages.filter(page=>page.selected).map(page=>page.page+1).join(',')||'none'});},[pages,onChange,mode]);
  return <section>{loading&&<p>{t('正在生成页面预览','Generating page previews')}</p>}{error&&<p role="alert">{error}</p>}{!!pages.length&&<><div className="tool-settings"><button onClick={()=>setPages(values=>values.map(page=>({...page,selected:true})))}>{t('全选','Select all')}</button><button onClick={()=>setPages(values=>values.map(page=>({...page,selected:false})))}>{t('取消选择','Clear selection')}</button>{mode==='pdf.organize'&&<><button onClick={()=>setPages(values=>values.map(page=>page.selected?{...page,rotation:(page.rotation+90)%360}:page))}>{t('旋转所选','Rotate selected')}</button><button onClick={()=>setPages(values=>values.filter(page=>!page.selected))}>{t('删除所选','Delete selected')}</button></>}</div><div className="pdf-page-grid">{pages.map((page,index)=><div key={page.page} draggable={mode==='pdf.organize'} onDragStart={()=>drag.current=index} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();setPages(values=>{const copy=[...values];if(drag.current>=0){const [moved]=copy.splice(drag.current,1);copy.splice(index,0,moved);}drag.current=-1;return copy;});}}><label><input type="checkbox" checked={page.selected} onChange={event=>setPages(values=>values.map((value,at)=>at===index?{...value,selected:event.target.checked}:value))}/>{t('原页面','Source page')} {page.page+1}</label><img src={page.thumbnail} alt={`${t('页面','Page')} ${page.page+1}`} style={{transform:`rotate(${page.rotation}deg)`}}/><div><button disabled={index===0} aria-label={t('前移页面','Move page earlier')} onClick={()=>setPages(values=>{const copy=[...values];[copy[index-1],copy[index]]=[copy[index],copy[index-1]];return copy;})}>←</button><button disabled={index===pages.length-1} aria-label={t('后移页面','Move page later')} onClick={()=>setPages(values=>{const copy=[...values];[copy[index+1],copy[index]]=[copy[index],copy[index+1]];return copy;})}>→</button></div></div>)}</div></>}</section>;
}
