import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
const fixture=(name:string,mimeType:string)=>({name,mimeType,buffer:readFileSync(resolve(__dirname,'../fixtures',name))});
const run=(page:import('@playwright/test').Page)=>page.getByRole('button',{name:'处理并导出',exact:true}).click();
test('imported text edits are authoritative and errors retain previous result',async({page})=>{
 await page.goto('/tools/data/json-format');await page.getByLabel('选择文件',{exact:true}).setInputFiles({name:'data.json',mimeType:'application/json',buffer:Buffer.from('{"old":1}')});await expect(page.getByLabel('输入文本',{exact:true})).toHaveValue('{"old":1}');await page.getByLabel('输入文本',{exact:true}).fill('{"new":2}');await page.getByRole('button',{name:'处理文本',exact:true}).click();await expect(page.locator('.tool-result')).toContainText('"new": 2');await page.getByLabel('缩进',{exact:true}).selectOption('4');await expect(page.locator('.result-stale')).toBeVisible();await expect(page.locator('.tool-result')).toContainText('"new": 2');await page.getByLabel('输入文本',{exact:true}).fill('{bad}');await page.getByRole('button',{name:'处理文本',exact:true}).click();await expect(page.locator('.tool-page').getByRole('alert')).toContainText('JSON');await expect(page.locator('.tool-result')).toContainText('"new": 2');
});
test('adding files in stages preserves both inputs and results survive removal',async({page})=>{
 await page.goto('/tools/archive/zip-create');for(const name of ['one.txt','two.txt'])await page.getByLabel('选择文件',{exact:true}).setInputFiles({name,mimeType:'text/plain',buffer:Buffer.from(name)});await expect(page.locator('.tool-file-list>div')).toHaveCount(2);await run(page);await expect(page.locator('.tool-result')).toContainText('files.zip');await page.getByRole('button',{name:'移除',exact:true}).last().click();await expect(page.locator('.tool-file-list>div')).toHaveCount(1);await expect(page.locator('.result-stale')).toBeVisible();await expect(page.locator('.tool-result')).toBeVisible();
});
test('PDF page text and thumbnail selection share state and all-page deletion is rejected',async({page})=>{
 await page.goto('/tools/pdf/delete-pages');await page.getByLabel('选择文件',{exact:true}).setInputFiles(fixture('pages.pdf','application/pdf'));await expect(page.locator('.pdf-page-grid img')).toHaveCount(3);await expect(page.getByLabel('原页面 1',{exact:true})).not.toBeChecked();await page.getByLabel('页码（all 或 1,3-5）',{exact:true}).fill('2');await expect(page.getByLabel('原页面 2',{exact:true})).toBeChecked();await page.getByLabel('原页面 3',{exact:true}).check();await expect(page.getByLabel('页码（all 或 1,3-5）',{exact:true})).toHaveValue('2,3');await page.getByLabel('页码（all 或 1,3-5）',{exact:true}).fill('1-3');await run(page);await expect(page.locator('.tool-page').getByRole('alert')).toContainText('保留一页');await expect(page.locator('.tool-result')).toHaveCount(0);
});
test('waveform handle updates exact trim values and the exported WAV has that duration',async({page})=>{
 await page.goto('/tools/audio/trim');await page.getByLabel('选择文件',{exact:true}).setInputFiles(fixture('sample.wav','audio/wav'));await page.getByRole('button',{name:'生成波形',exact:true}).click();await expect(page.locator('.media-wave svg line')).not.toHaveCount(2,{timeout:30000});await page.getByLabel('波形起点手柄',{exact:true}).focus();await page.keyboard.press('ArrowRight');await expect(page.getByLabel('开始时间',{exact:true})).not.toHaveValue('00:00:00');await page.getByLabel('开始时间',{exact:true}).fill('0.1');await page.getByLabel('结束时间',{exact:true}).fill('0.5');await page.getByLabel('输出格式',{exact:true}).selectOption('wav');await run(page);await expect(page.locator('.tool-result audio')).toBeVisible({timeout:30000});await page.screenshot({path:'../../docs/screenshots/workbench-audio-trim.png'});const pending=page.waitForEvent('download');await page.locator('.tool-result').getByRole('button',{name:/^下载 /}).click();const download=await pending;const {execFileSync}=await import('node:child_process');const report=execFileSync('ffprobe',['-v','error','-show_entries','format=duration','-of','json',(await download.path())!],{encoding:'utf8'});expect(Number(JSON.parse(report).format.duration)).toBeCloseTo(.4,1);
});
test('rendered PDF proof is invalidated after changing the watermark',async({page})=>{
 await page.goto('/tools/pdf/watermark');await page.getByLabel('选择文件',{exact:true}).setInputFiles(fixture('sample.pdf','application/pdf'));await page.getByLabel('水印文字',{exact:true}).fill('FIRST');await expect(page.locator('.pdf-proof img')).toBeVisible({timeout:30000});await page.getByRole('button',{name:'检查实际渲染',exact:true}).click();await expect(page.getByAltText('实际渲染预览')).toBeVisible({timeout:30000});await page.getByLabel('水印文字',{exact:true}).fill('SECOND');await expect(page.getByAltText('实际渲染预览')).toHaveCount(0);
});
test('language persists across tool and history navigation',async({page})=>{
 await page.goto('/tools/data/json-format');await page.getByRole('button',{name:'EN',exact:true}).click();await expect(page.getByRole('heading',{name:'Format JSON'})).toBeVisible();await page.getByRole('link',{name:'History',exact:true}).click();await expect(page.getByRole('heading',{name:'History',exact:true})).toBeVisible();await expect(page.locator('html')).toHaveAttribute('lang','en');
});
test('one invalid image leaves successful batch exports accessible',async({page})=>{
 await page.goto('/tools/image/convert');await page.getByLabel('选择文件',{exact:true}).setInputFiles([fixture('sample.png','image/png'),{name:'broken.png',mimeType:'image/png',buffer:Buffer.from('broken')}]);await run(page);await expect(page.locator('.tool-result')).toContainText('1 成功');await expect(page.locator('.tool-result')).toContainText('1 失败');await expect(page.locator('.tool-result').getByRole('button',{name:/^下载 /})).toBeVisible();await expect(page.locator('.tool-result').getByRole('button',{name:'重试失败项',exact:true})).toBeVisible();
});
test('image result is handed to the next compatible tool without another upload',async({page})=>{
 await page.goto('/tools/image/compress');await page.getByLabel('选择文件',{exact:true}).setInputFiles(fixture('sample.png','image/png'));await run(page);await expect(page.locator('.tool-result')).toBeVisible();await page.locator('.tool-result').getByRole('button',{name:'继续处理结果',exact:true}).click();await page.locator('.handoff-tools').getByRole('link',{name:'调整图片尺寸',exact:true}).click();await expect(page).toHaveURL(/image\/resize$/);await expect(page.locator('.tool-file-list>div')).toHaveCount(1);await expect(page.getByLabel('输出格式',{exact:true})).toHaveValue('preserve');await page.getByLabel('宽度（像素）',{exact:true}).fill('40');await run(page);await expect(page.locator('.result-preview')).toBeVisible();await expect.poll(()=>page.locator('.result-preview').evaluate((image:HTMLImageElement)=>image.naturalWidth)).toBe(40);
});
test('CSV preview follows delimiter and imported values',async({page})=>{
 await page.goto('/tools/data/csv-json');await page.getByLabel('输入文本',{exact:true}).fill('name;age\n张三;20');await page.getByLabel('分隔符',{exact:true}).selectOption(';');await page.getByRole('button',{name:'检查输入结构',exact:true}).click();await expect(page.locator('.data-grid')).toContainText('张三');await expect(page.locator('.data-grid th')).toHaveCount(2);await page.getByRole('button',{name:'处理文本',exact:true}).click();await expect(page.locator('.tool-result')).toContainText('"age": "20"');
});
test('video GIF preview renders a real bounded image and selected frame export can be browsed',async({page})=>{
 await page.goto('/tools/video/gif');await page.getByLabel('选择文件',{exact:true}).setInputFiles(fixture('sample.mp4','video/mp4'));await expect(page.locator('.media-editor video')).toBeVisible();await page.getByRole('button',{name:'生成轻量 GIF 预览',exact:true}).click();await expect(page.getByAltText('GIF 片段预览')).toBeVisible({timeout:30000});await expect.poll(()=>page.getByAltText('GIF 片段预览').evaluate((image:HTMLImageElement)=>image.naturalWidth)).toBeGreaterThan(0);expect(await page.getByAltText('GIF 片段预览').evaluate((image:HTMLImageElement)=>image.naturalWidth)).toBeLessThanOrEqual(240);
 await page.goto('/tools/video/frames');await page.getByLabel('选择文件',{exact:true}).setInputFiles(fixture('sample.mp4','video/mp4'));await page.getByLabel('模式',{exact:true}).selectOption('single');await page.getByLabel('指定时间',{exact:true}).fill('0.5');await run(page);await expect(page.locator('.tool-result')).toBeVisible({timeout:30000});await page.getByRole('button',{name:'浏览文件与选择下载',exact:true}).click();await expect(page.locator('.archive-entries')).toContainText('frame_001.jpg');await page.locator('.archive-entries').getByRole('button',{name:'预览',exact:true}).click();await expect(page.locator('.tool-result .result-preview')).toBeVisible();
});
test('text result handoff opens the next editor with the generated content',async({page})=>{
 await page.goto('/tools/data/json-format');await page.getByLabel('输入文本',{exact:true}).fill('{"title":"交接示例"}');await page.getByRole('button',{name:'处理文本',exact:true}).click();await page.getByRole('button',{name:'继续处理结果',exact:true}).click();await page.locator('.handoff-tools').getByRole('link',{name:'JSON 转 YAML',exact:true}).click();await expect(page.getByLabel('输入文本',{exact:true})).toHaveValue(/交接示例/);await page.getByRole('button',{name:'处理文本',exact:true}).click();await expect(page.locator('.tool-result')).toContainText('title: 交接示例');
});
