'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Star,Upload,ArrowLeft,X} from 'lucide-react';
import type {ToolDefinition,ToolResult} from '@/lib/tools/registry';
import {executeTool} from '@/lib/tools/execution';
import {recordToolUse,readToolPreferences,toggleFavorite} from '@/lib/tools/preferences';
import {downloadServerJob} from '@/lib/server-api';
import {saveHistory} from '@/lib/history';
import {loadToolPresets,storeToolPreset,safeSettings,type ToolPreset} from '@/lib/tools/presets';
import {createZip} from '@/lib/tools/archive';
import ArchiveInspector from './tools/archive-inspector';
import {renamedFiles} from '@/lib/tools/archive';
import PdfOrganizer from './tools/pdf-organizer';
import CropEditor from './tools/crop-editor';
import {Preview} from './tools/preview';
function download(blob:Blob,name:string) { const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
const reportNames:Record<string,string>={filename:'文件名',extension:'扩展名',actual_format:'实际格式',size:'文件大小',mime:'MIME 类型',magic_signature:'文件签名',format:'格式',width:'宽度',height:'高度',pixels:'像素数',color_mode:'色彩模式',alpha:'透明通道',frames:'帧数',animated:'动画',icc_bytes:'色彩配置大小',exif:'拍摄信息',pages:'页数',encrypted:'加密',metadata:'元数据',container:'容器',streams:'媒体轨道',images:'内嵌图片数',fonts:'字体数',title:'标题',author:'作者',subject:'主题',keywords:'关键词',creator:'创建程序',producer:'生成程序',creationDate:'创建时间',modDate:'修改时间',Checksum:'校验结果'};
function Result({result,language}: {result:ToolResult;language:'zh'|'en'}) {
  const t=(zh:string,en:string)=>language==='zh'?zh:en;
  if (result.kind==='server-files') return <>{result.files.map(file=><button key={file.jobId} onClick={()=>downloadServerJob(file.jobId)}>{t('下载','Download')} {file.name}</button>)}</>;
  if (result.kind==='server-file') return <button className="primary-button" onClick={()=>downloadServerJob(result.jobId)}>{t('下载','Download')} {result.name}</button>;
  if (result.kind==='file'||result.kind==='archive') return <><Preview blob={result.blob} alt={result.name}/><button className="primary-button" onClick={()=>download(result.blob,result.name)}>{t('下载','Download')} {result.name} · {(result.blob.size/1024).toFixed(1)} KB</button></>;
  if (result.kind==='files') return <><button onClick={()=>void createZip(result.files).then(blob=>download(blob,'results.zip'))}>{t('下载全部 ZIP','Download all as ZIP')}</button>{result.files.map((file,index)=><button key={index} onClick={()=>download(file.blob,file.name)}>{file.name}</button>)}</>;
  const value=result.kind==='text'?result.text:result.fields.map(field=>`${field.label}: ${field.value}`).join('\n');
  return <><div className="tool-result-actions"><button onClick={()=>void navigator.clipboard.writeText(value)}>{t('复制','Copy')}</button><button onClick={()=>download(new Blob([value],{type:'text/plain'}),result.kind==='text'?result.name??'result.txt':'report.txt')}>{t('下载','Download')}</button></div>{result.kind==='text'?<pre>{result.text==='JSON valid'?t('JSON 有效','JSON valid'):result.text}</pre>:<dl className="tool-report">{result.fields.map((field,index)=><div key={index}><dt>{language==='zh'?reportNames[field.label]??field.label:field.label}</dt><dd>{language==='zh'&&field.value==='Match'?'一致':language==='zh'&&field.value==='Mismatch'?'不一致':field.value}</dd></div>)}</dl>}</>;
}
function RenamePreview({files,settings}:{files:File[];settings:Record<string,unknown>}) {try{return <dl className="tool-report">{renamedFiles(files,settings).map((file,index)=><div key={index}><dt>{files[index].name}</dt><dd>{file.name}</dd></div>)}</dl>;}catch{return null;}}
export default function ToolPage({tool}: {tool:ToolDefinition}) {
  const [language,setLanguage]=useState<'zh'|'en'>('zh'),[files,setFiles]=useState<File[]>([]),[settings,setSettings]=useState<Record<string,unknown>>(()=>Object.fromEntries((tool.settingsSchema??[]).map(field=>[field.key,field.defaultValue??'']))),[result,setResult]=useState<ToolResult|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[favorite,setFavorite]=useState(false),[presets,setPresets]=useState<ToolPreset[]>([]),[presetName,setPresetName]=useState('');
  const input=useRef<HTMLInputElement>(null),controller=useRef<AbortController|null>(null);
  const t=(zh:string,en:string)=>language==='zh'?zh:en;
  useEffect(()=>{setPresets(loadToolPresets());try{const replay=JSON.parse(sessionStorage.getItem('convertbox-replay')??'null');if(replay?.toolId===tool.id){setSettings(old=>({...old,...safeSettings(replay.settings)}));sessionStorage.removeItem('convertbox-replay');}}catch{}recordToolUse(tool.id);setFavorite(readToolPreferences().favorites.includes(tool.id));return()=>controller.current?.abort();},[tool.id]);
  const add=(incoming:File[])=>{if (busy)return;setFiles(tool.multipleInputSupport||tool.batchSupport?incoming:incoming.slice(0,1));setResult(null);setError('');};
  const update=useCallback((values:Record<string,unknown>)=>{setSettings(old=>({...old,...values}));setResult(null);},[]);
  const run=async()=>{setBusy(true);setError('');setResult(null);setProgress(0);const abort=new AbortController();controller.current=abort;try{const value=await executeTool({toolId:tool.id,files,settings},abort.signal,setProgress);setResult(value);setSettings(old=>{const next={...old};delete next.password;delete next.confirm_password;return next;});void saveHistory({id:crypto.randomUUID(),toolId:tool.id,status:'COMPLETED',name:files.map(file=>file.name).join(', ')||tool.name[language],inputFormat:files[0]?.name.split('.').pop()??'text',outputFormat:String(settings.output??value.kind),inputSize:files.reduce((sum,file)=>sum+file.size,0),outputSize:value.kind==='file'||value.kind==='archive'?value.blob.size:value.kind==='server-file'?value.size:0,createdAt:Date.now(),settings:safeSettings(settings)}).catch(()=>{});}catch(error){setError(error instanceof Error?error.message:String(error));}finally{if(tool.id==='pdf.protect')setSettings(old=>({...old,password:'',confirm_password:''}));setBusy(false);controller.current=null;}};
  return <div className="tools-home-shell"><header className="tools-home-header glass"><Link href="/"><ArrowLeft size={17}/> {t('工具中心','Tools')}</Link><div><button className="favorite-button" aria-label={t('收藏','Favorite')} onClick={()=>setFavorite(toggleFavorite(tool.id).favorites.includes(tool.id))}><Star size={18} fill={favorite?'currentColor':'none'}/></button><select aria-label={t('主题','Theme')} onChange={event=>document.documentElement.dataset.theme=event.target.value}><option value="light">{t('浅色','Light')}</option><option value="dark">{t('深色','Dark')}</option></select><button onClick={()=>setLanguage(value=>value==='zh'?'en':'zh')}>{language==='zh'?'EN':'中文'}</button></div></header><main className="tool-page glass"><div className="tool-page-heading"><h1>{tool.name[language]}</h1><span>{tool.processing==='local'?t('本地处理','Local processing'):tool.processing==='server'?t('服务器处理','Server processing'):t('本地优先','Local when supported')}</span></div><div className="tool-page-body"><section className="tool-input-panel"><input ref={input} aria-label={t('选择文件','Choose files')} type="file" hidden multiple={tool.multipleInputSupport||tool.batchSupport} accept={tool.acceptedInputs.includes('*')?undefined:tool.acceptedInputs.join(',')} onChange={event=>add(Array.from(event.target.files??[]))}/>{tool.category==='data'?<textarea aria-label={t('输入文本','Input text')} placeholder={t('粘贴文本，或选择文件','Paste text or choose a file')} value={String(settings.text??'')} onChange={event=>update({text:event.target.value})}/>:<div className={`tool-drop ${files.length?'has-files':''}`} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();add(Array.from(event.dataTransfer.files));}}><Upload size={32}/><h2>{t('拖入文件','Drop files')}</h2><button onClick={()=>input.current?.click()} disabled={busy}>{t('选择文件','Choose files')}</button></div>}{tool.category==='data'&&<button onClick={()=>input.current?.click()} disabled={busy}>{t('上传文本文件','Upload text file')}</button>}<div className="tool-file-list">{files.map((file,index)=><div key={index}><span>{file.name} · {(file.size/1024).toFixed(1)} KB</span>{tool.multipleInputSupport&&<><button disabled={busy||index===0} aria-label={t('前移文件','Move file earlier')} onClick={()=>setFiles(values=>{const copy=[...values];[copy[index-1],copy[index]]=[copy[index],copy[index-1]];return copy;})}>↑</button><button disabled={busy||index===files.length-1} aria-label={t('后移文件','Move file later')} onClick={()=>setFiles(values=>{const copy=[...values];[copy[index+1],copy[index]]=[copy[index],copy[index+1]];return copy;})}>↓</button></>}<button aria-label={t('移除','Remove')} disabled={busy} onClick={()=>setFiles(values=>values.filter((_,at)=>at!==index))}><X size={16}/></button></div>)}</div>{tool.id==='archive.inspect'&&files[0]&&<ArchiveInspector file={files[0]} language={language}/>}
{tool.id==='file.rename'&&files.length>0&&<RenamePreview files={files} settings={settings}/>}
{tool.id==='image.crop'&&files[0]&&<CropEditor file={files[0]} onChange={update} language={language}/>}{['pdf.organize','pdf.extract-pages','pdf.delete-pages'].includes(tool.id)&&files[0]&&<PdfOrganizer file={files[0]} onChange={update} language={language} mode={tool.id}/>}</section><section className="tool-control-panel">{tool.id!=='pdf.protect'&&<div className="tool-settings"><label>{t('预设','Preset')}<select defaultValue="" onChange={event=>{const preset=presets.find(value=>value.id===event.target.value);if(preset)update(preset.settings);}}><option value="">{t('选择预设','Choose preset')}</option>{presets.filter(preset=>preset.toolId===tool.id).map(preset=><option key={preset.id} value={preset.id}>{preset.name}</option>)}</select></label><label>{t('预设名称','Preset name')}<input maxLength={50} value={presetName} onChange={event=>setPresetName(event.target.value)}/></label><button disabled={!presetName.trim()||busy} onClick={()=>{setPresets(storeToolPreset(tool.id,presetName,settings));setPresetName('');}}>{t('保存','Save')}</button></div>}<fieldset disabled={busy} className="tool-settings">{tool.settingsSchema?.map(field=><label key={field.key}>{field.label[language]}{field.kind==='select'?<select value={String(settings[field.key]??'')} onChange={event=>update({[field.key]:event.target.value})}>{field.options?.map(option=><option key={option.value} value={option.value}>{option.label[language]}</option>)}</select>:<input type={field.kind==='boolean'?'checkbox':field.kind==='number'?'number':field.key==='password'||field.key==='confirm_password'?'password':'text'} autoComplete="off" step={field.kind==='number'?'any':undefined} min={field.min} max={field.max} checked={field.kind==='boolean'?Boolean(settings[field.key]):undefined} value={field.kind==='boolean'?undefined:String(settings[field.key]??'')} onChange={event=>update({[field.key]:field.kind==='boolean'?event.target.checked:field.kind==='number'?Number(event.target.value):event.target.value})}/>}</label>)}</fieldset>{tool.id==='file.hash'&&settings.algorithm!=='sha256'&&<p>{t('MD5 / SHA-1 仅用于文件完整性校验，不适合密码或安全用途。','MD5 / SHA-1 are for file integrity checks, not passwords or security.')}</p>}<button className="primary-button" disabled={busy||(!files.length&&tool.category!=='data')} onClick={()=>void run()}>{busy?t('处理中','Processing'):t('开始处理','Run')}</button>{busy&&<progress value={progress} max="1"/>}{error&&<p role="alert">{error}</p>}{result&&<div className="tool-result" aria-live="polite">{(tool.id==='image.compress'||tool.id==='video.compress')&&files.length===1&&(result.kind==='file'||result.kind==='server-file')&&<p>{(files[0].size/1024).toFixed(1)} KB → {((result.kind==='file'?result.blob.size:result.size)/1024).toFixed(1)} KB · {((1-(result.kind==='file'?result.blob.size:result.size)/files[0].size)*100).toFixed(1)}% {t('体积减少','smaller')}</p>}<Result result={result} language={language}/></div>}</section></div></main></div>;
}
