/* eslint-disable @next/next/no-img-element */
'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Star,Upload,X} from 'lucide-react';
import type {ToolDefinition,ToolResult} from '@/lib/tools/registry';
import {toolError} from '@/lib/tools/errors';
import {executeTool} from '@/lib/tools/execution';
import {recordToolUse,readToolPreferences,toggleFavorite} from '@/lib/tools/preferences';
import {getServerCapabilities,deleteServerJob,pollServerJob,type ServerCapabilities} from '@/lib/server-api';
import {saveHistory} from '@/lib/history';
import {loadToolPresets,storeToolPreset,safeSettings,type ToolPreset} from '@/lib/tools/presets';
import {renamedFiles} from '@/lib/tools/archive';
import {inputSnapshot,readDraft,storeDraft,takeFiles,forgetTask} from '@/lib/tools/workbench-state';
import {visibleSetting} from '@/lib/tools/catalog';
import {useInterface} from '@/lib/use-interface';
import WorkbenchShell from './tools/workbench-shell';
import ArchiveInspector from './tools/archive-inspector';
import PdfOrganizer from './tools/pdf-organizer';
import PdfPreview from './tools/pdf-preview';
import CropEditor from './tools/crop-editor';
import MediaEditor,{seconds} from './tools/media-editor';
import MergeAudioPreview from './tools/merge-audio-preview';
import DataInspector from './tools/data-inspector';
import FaviconPreview from './tools/favicon-preview';
import ResultPanel from './tools/result-panel';
import {useBlobUrl} from './tools/preview';
import {detectFileType} from '@detection/detect';
import type {FileDescriptor} from '@shared/index';
import {toolAvailable} from '@/lib/tools/availability';
function OriginalImage({file,tool,settings,onInfo}:{file:File;tool:string;settings:Record<string,unknown>;onInfo:(width:number,height:number)=>void}){const url=useBlobUrl(file);return <div className="original-image" style={settings.output==='jpg'?{background:String(settings.background??'#ffffff')}:undefined}><img src={url} alt={file.name} onLoad={event=>onInfo(event.currentTarget.naturalWidth,event.currentTarget.naturalHeight)} style={{transform:`rotate(${tool==='image.rotate'?Number(settings.rotation??0):0}deg) scale(${tool==='image.flip'&&settings.direction==='horizontal'?-1:1},${tool==='image.flip'&&settings.direction==='vertical'?-1:1})`}}/></div>;}
function PlaylistItem({file,onDuration}:{file:File;onDuration:(n:number)=>void}){const url=useBlobUrl(file);return <audio controls src={url} preload="metadata" onLoadedMetadata={event=>{if(Number.isFinite(event.currentTarget.duration))onDuration(event.currentTarget.duration);}}/>;}
function RenamePreview({files,settings,language}:{files:File[];settings:Record<string,unknown>;language:'zh'|'en'}){try{const values=renamedFiles(files,settings);return <><p>{language==='zh'?'生成重命名后的 ZIP，设备上的原文件保持不变。':'Downloads renamed copies as a ZIP; original files remain on your device.'}</p><dl className="tool-report">{values.map((file,i)=><div key={i}><dt>{files[i].name}</dt><dd>{file.name}{file.adjusted?(language==='zh'?'（已避免重名）':' (collision resolved)'):''}</dd></div>)}</dl></>;}catch(error){return <p role="alert">{toolError(error,language)}</p>;}}
export default function ToolPage({tool}:{tool:ToolDefinition}){
 const {language,setLanguage,theme,setTheme}=useInterface(),[files,setFiles]=useState<File[]>([]),[activeFile,setActiveFile]=useState(0),[settings,setSettings]=useState<Record<string,unknown>>(()=>Object.fromEntries((tool.settingsSchema??[]).map(field=>[field.key,field.defaultValue??'']))),[result,setResult]=useState<ToolResult|null>(null),[snapshot,setSnapshot]=useState(''),[resultInputs,setResultInputs]=useState<File[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[stage,setStage]=useState(''),[favorite,setFavorite]=useState(false),[presets,setPresets]=useState<ToolPreset[]>([]),[presetName,setPresetName]=useState(''),[descriptor,setDescriptor]=useState<FileDescriptor|null>(null),[capabilities,setCapabilities]=useState<ServerCapabilities|null>(null),[serviceError,setServiceError]=useState(false),[sizes,setSizes]=useState({width:0,height:0}),[durations,setDurations]=useState<Record<string,number>>({}),[search,setSearch]=useState(''),[transformUndo,setTransformUndo]=useState<Record<string,unknown>[]>([]);
 const input=useRef<HTMLInputElement>(null),folder=useRef<HTMLInputElement>(null),controller=useRef<AbortController|null>(null),jobs=useRef<string[]>([]),current=useRef({files,settings,result,snapshot,resultInputs});current.current={files,settings,result,snapshot,resultInputs};
 const t=(zh:string,en:string)=>language==='zh'?zh:en,stale=!!result&&snapshot!==inputSnapshot(files,settings);
 const update=useCallback((values:Record<string,unknown>)=>{if(['image.rotate','image.flip'].includes(tool.id)&&('rotation' in values||'direction' in values))setTransformUndo(previous=>[...previous.slice(-9),{rotation:current.current.settings.rotation,direction:current.current.settings.direction}]);setSettings(old=>({...old,...values}));setError('');},[tool.id]);
 useEffect(()=>{setPresets(loadToolPresets());setFavorite(readToolPreferences().favorites.includes(tool.id));const draft=readDraft(tool.id);if(draft){setFiles(draft.files);setSettings(draft.settings);setResult(draft.result);setSnapshot(draft.snapshot);setResultInputs(draft.resultInputs);}const incoming=takeFiles();if(incoming.length){setFiles(incoming);setResult(null);}
  try{const replay=JSON.parse(sessionStorage.getItem('convertbox-replay')??'null');if(replay?.toolId===tool.id){setSettings(old=>({...old,...safeSettings(replay.settings)}));sessionStorage.removeItem('convertbox-replay');setError(t('已复用设置，请选择文件。','Settings restored. Choose a file.'));}}catch{}
  void getServerCapabilities().then(setCapabilities).catch(()=>setServiceError(true));
  return()=>{storeDraft(tool.id,current.current);controller.current?.abort();};
 // Language does not trigger draft reloading.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[tool.id]);
 useEffect(()=>{let active=true;setDescriptor(null);if(files[activeFile]??files[0])void detectFileType(files[activeFile]??files[0]).then(value=>{if(active)setDescriptor(value);}).catch(()=>{});return()=>{active=false;};},[files,activeFile]);
 const add=async(incoming:File[],replace=false)=>{if(busy)return;setError('');if(!(tool.multipleInputSupport||tool.batchSupport)&&incoming.length>1){setError(t('此工具一次处理一个文件，请只选择一份。','Choose one file for this tool.'));return;}
  if(tool.category==='data'){if(incoming[0]?.size>8*1024*1024){setError(t('文本不能超过 8 MB。','Text cannot exceed 8 MB.'));return;}try{const text=new TextDecoder('utf-8',{fatal:true}).decode(await incoming[0].arrayBuffer());setFiles([incoming[0]]);update({text});}catch{setError(t('请使用 UTF-8 文本文件。','Use a UTF-8 text file.'));}return;}
  setFiles(old=>replace||!(tool.multipleInputSupport||tool.batchSupport)?incoming:[...old,...incoming.filter(file=>!old.some(existing=>existing.name===file.name&&existing.size===file.size&&existing.lastModified===file.lastModified))]);
 };
 const validity=()=>{
  if(!files.length&&tool.category!=='data')return t('请先选择文件。','Choose a file.');if(tool.category==='data'&&!String(settings.text??'').trim())return t('请输入内容。','Enter some text.');
  if(tool.id==='audio.merge'||tool.id==='pdf.merge'){if(files.length<2)return t('请至少选择两个文件。','Choose at least two files.');}
  for(const field of tool.settingsSchema??[]){if(field.kind==='number'){const value=Number(settings[field.key]);if(!Number.isFinite(value)||(field.min!==undefined&&value<field.min)||(field.max!==undefined&&value>field.max))return t(`${field.label.zh}超出范围。`,`${field.label.en} is outside the allowed range.`);}}
  if(tool.id.endsWith('.trim')&&Number(settings.media_duration)&&seconds(settings.end)>Number(settings.media_duration)+.05)return t('选区超出文件时长。','Selection exceeds the file duration.');
  if(tool.id==='video.gif'&&Number(settings.media_duration)&&seconds(settings.start)+Number(settings.duration)>Number(settings.media_duration)+.05)return t('GIF 选区超出文件时长。','GIF selection exceeds the file duration.');
  if(tool.id==='video.frames'&&settings.mode==='interval'&&Number(settings.media_duration)/Number(settings.interval)>100)return t('最多提取 100 帧，请增大间隔。','Increase the interval to extract at most 100 frames.');
  if(tool.id==='audio.merge'&&files.length>20)return t('最多合并 20 个音频文件。','Merge up to 20 audio files.');
  if(tool.id==='pdf.protect'&&(!settings.password||settings.password!==settings.confirm_password))return t('请填写一致的密码。','Enter matching passwords.');
  if(tool.id==='pdf.unlock'&&!settings.password)return t('请填写文件的已有密码。','Enter the existing file password.');
  if(tool.id==='pdf.watermark'&&!String(settings.text??'').trim())return t('请输入水印文字。','Enter watermark text.');
  if(tool.id.endsWith('.trim')&&!(seconds(settings.end)>seconds(settings.start)))return t('结束时间必须晚于开始时间。','End must be later than start.');
  if(['pdf.extract-pages','pdf.delete-pages'].includes(tool.id)&&['none',''].includes(String(settings.pages)))return t('请选择页面。','Select pages.');
  if(tool.id==='pdf.delete-pages'&&Number(settings.pdf_page_count)){const selected=new Set<number>();for(const part of String(settings.pages).split(',')){const [first,last]=part.trim().split('-').map(Number);for(let page=first;page<=(last||first)&&page<=Number(settings.pdf_page_count);page++)if(page>0)selected.add(page);}if(selected.size>=Number(settings.pdf_page_count))return t('不能删除全部页面，请至少保留一页。','Keep at least one page.');}
  if(tool.id==='pdf.delete-pages'&&String(settings.pages).trim().toLowerCase()==='all')return t('不能删除全部页面，请至少保留一页。','Keep at least one page.');
  if(tool.processing==='server'&&serviceError)return t('处理服务暂时离线，请重试。','Processing service is offline. Retry later.');
  return '';
 };
 const run=async(retryNames?:string[])=>{if(busy)return;const invalid=validity();if(invalid){setError(invalid);return;}const source=retryNames?files.filter(file=>retryNames.includes(file.name)):files,runSettings={...settings},runSnapshot=inputSnapshot(files,settings);setBusy(true);setError('');setProgress(0);jobs.current=[];const abort=new AbortController();controller.current=abort;const partial:({kind:'file';blob:Blob;name:string}|{kind:'server-file';jobId:string;name:string;size:number})[]=[],failures:{name:string;error:string}[]=[];
  try{const value=await executeTool({toolId:tool.id,files:source,settings:runSettings},abort.signal,setProgress,{stage:setStage,job:job=>jobs.current.push(job.id),item:(index,value,error)=>{if(value&&(value.kind==='file'||value.kind==='server-file'))partial.push(value);if(error)failures.push({name:source[index].name,error:toolError(new Error(error),language)});setResult({kind:'batch',items:[...partial],failures:[...failures]});setSnapshot(runSnapshot);setResultInputs(files);}});
   setResult(retryNames&&result?.kind==='batch'&&value.kind==='batch'?{...value,items:[...result.items,...value.items]}:value);setSnapshot(runSnapshot);setResultInputs(files);recordToolUse(tool.id);
   const name=value.kind==='file'||value.kind==='archive'||value.kind==='server-file'?value.name:value.kind==='text'?value.name??'result.txt':value.kind==='report'?'report.txt':'results.zip';
   void saveHistory({id:crypto.randomUUID(),toolId:tool.id,status:value.kind==='batch'&&value.failures.length?'PARTIAL':'COMPLETED',name:source.map(file=>file.name).join(', ')||tool.name[language],inputFormat:source[0]?.name.split('.').pop()??'text',outputFormat:name.split('.').pop()??'file',inputSize:source.reduce((n,file)=>n+file.size,0),outputSize:value.kind==='file'||value.kind==='archive'?value.blob.size:value.kind==='server-file'?value.size:0,createdAt:Date.now(),settings:safeSettings(runSettings),jobId:value.kind==='server-file'?value.jobId:undefined}).catch(()=>{});
  }catch(error){void saveHistory({id:crypto.randomUUID(),toolId:tool.id,status:abort.signal.aborted?'CANCELLED':'FAILED',name:source.map(file=>file.name).join(', ')||tool.name[language],inputFormat:source[0]?.name.split('.').pop()??'text',outputFormat:String(runSettings.output??'file'),inputSize:source.reduce((n,file)=>n+file.size,0),outputSize:0,createdAt:Date.now(),settings:safeSettings(runSettings)}).catch(()=>{});setError(abort.signal.aborted?t('已停止等待，已生成的结果仍可下载；服务器任务可在记录中恢复。','Stopped waiting. Existing results remain available; server jobs can be resumed from history.'):toolError(error,language));}finally{if(['pdf.protect','pdf.unlock'].includes(tool.id))setSettings(old=>({...old,password:'',confirm_password:''}));setBusy(false);controller.current=null;}
 };
 useEffect(()=>{const id=new URLSearchParams(location.search).get('resume');if(!id)return;const abort=new AbortController();controller.current=abort;setBusy(true);setStage('processing');void pollServerJob(id,job=>setProgress(job.progress??0),abort.signal).then(job=>{if(job.status==='COMPLETED'){setResult({kind:'server-file',jobId:id,name:job.outputName??'result',size:job.outputSize??0});setResultInputs([]);setSnapshot(inputSnapshot([],{}));}else setError(job.error??t('任务失败','Task failed'));}).catch(error=>{if(!abort.signal.aborted)setError(toolError(error,language));}).finally(()=>setBusy(false));return()=>abort.abort();
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[tool.id]);
 const cancel=async()=>{controller.current?.abort();for(const id of jobs.current){try{await deleteServerJob(id);forgetTask(id);}catch{setError(t('服务器正在处理此任务，无法立即终止；可在记录中查看结果。','This server job cannot stop immediately. Check its result in history.'));}}};
 const previewFile=files[activeFile]??files[0];
 const sourceWidth=descriptor?.width??sizes.width,sourceHeight=descriptor?.height??sizes.height;
 const desiredWidth=Number(settings.width)||0,desiredHeight=Number(settings.height)||0,percent=Number(settings.percent??100)/100;
 const expectedWidth=desiredWidth||(desiredHeight&&sourceHeight?Math.round(sourceWidth*desiredHeight/sourceHeight):Math.round(sourceWidth*percent));
 const expectedHeight=settings.lock_ratio!==false&&desiredWidth&&sourceWidth?Math.round(sourceHeight*desiredWidth/sourceWidth):desiredHeight||Math.round(sourceHeight*percent);
 const locate=(line:number,column:number)=>{const textarea=document.querySelector<HTMLTextAreaElement>('.data-editor textarea');if(!textarea)return;const rows=String(settings.text??'').split('\n');const at=rows.slice(0,line-1).reduce((n,row)=>n+row.length+1,0)+column-1;textarea.focus();textarea.setSelectionRange(at,at+1);textarea.scrollTop=Math.max(0,(line-3)*20);};
 const schema=(tool.settingsSchema??[]).filter(field=>visibleSetting(tool.id,field.key,settings));
 const action=tool.id==='file.hash'?t('计算校验值','Calculate checksum'):tool.id.startsWith('data.')?t('处理文本','Process text'):tool.id==='file.rename'?t('重命名并打包','Rename and package'):tool.id==='archive.inspect'?t('检查目录','Inspect directory'):tool.id==='archive.zip-extract'?t('提取文件','Extract files'):t('处理并导出','Process and export');
 const stageNames:Record<string,string>={local:t('本地处理','Processing locally'),uploading:t('正在上传','Uploading'),'rate-wait':t('上传限流，等待重试','Upload limited; waiting to retry'),queued:t('排队中','Queued'),processing:t('处理中','Processing'),completed:t('已完成','Completed')};
 return <WorkbenchShell language={language} theme={theme} onLanguage={()=>setLanguage(language==='zh'?'en':'zh')} onTheme={setTheme} category={tool.category} active={tool.id}><main className="tool-page glass"><div className="tool-page-heading"><h1>{tool.name[language]}</h1><button className="favorite-button" aria-label={t('收藏工具','Favorite tool')} onClick={()=>setFavorite(toggleFavorite(tool.id).favorites.includes(tool.id))}><Star size={18} fill={favorite?'currentColor':'none'}/></button></div>
 <div className="tool-page-body"><section className="tool-input-panel"><input ref={input} aria-label={t('选择文件','Choose files')} type="file" hidden multiple={tool.multipleInputSupport||tool.batchSupport} accept={tool.acceptedInputs.includes('*')?undefined:tool.acceptedInputs.join(',')} onChange={event=>{void add(Array.from(event.target.files??[]));event.target.value='';}}/><input ref={folder} type="file" hidden multiple {...{'webkitdirectory':''}} onChange={event=>{void add(Array.from(event.target.files??[]));event.target.value='';}}/>
 {tool.category==='data'?<><div className="tool-settings"><button disabled={busy} onClick={()=>input.current?.click()}>{t('导入文本文件','Import text file')}</button><label>{t('查找','Find')}<input value={search} onChange={event=>setSearch(event.target.value)}/></label><button onClick={()=>{const textarea=document.querySelector<HTMLTextAreaElement>('.data-editor textarea');const at=String(settings.text??'').indexOf(search);if(textarea&&at>=0){textarea.focus();textarea.setSelectionRange(at,at+search.length);}}}>{t('定位','Locate')}</button></div><div className="data-editor"><pre aria-hidden="true">{String(settings.text??'').split('\n').slice(0,5000).map((_,i)=>i+1).join('\n')}</pre><textarea disabled={busy} aria-label={t('输入文本','Input text')} placeholder={t('粘贴文本，或导入文件后编辑','Paste text or import a file to edit')} value={String(settings.text??'')} onScroll={event=>{const pre=event.currentTarget.previousElementSibling;if(pre)pre.scrollTop=event.currentTarget.scrollTop;}} onChange={event=>update({text:event.target.value})}/></div><DataInspector toolId={tool.id} settings={settings} language={language} onLocate={locate}/></>:!files.length?<div className="tool-drop" onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();void add(Array.from(event.dataTransfer.files));}}><Upload size={32}/><h2>{t('拖入文件','Drop files')}</h2><button onClick={()=>input.current?.click()} disabled={busy}>{t('选择文件','Choose files')}</button><p>{tool.acceptedInputs.join(' · ')}</p></div>:<div className="file-actions" onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();void add(Array.from(event.dataTransfer.files));}}><button disabled={busy} onClick={()=>input.current?.click()}>{t(tool.multipleInputSupport||tool.batchSupport?'添加文件':'替换文件',tool.multipleInputSupport||tool.batchSupport?'Add files':'Replace file')}</button>{['archive.zip-create','file.rename'].includes(tool.id)&&<button disabled={busy} onClick={()=>folder.current?.click()}>{t('添加文件夹','Add folder')}</button>}</div>}
 <div className="tool-file-list">{files.map((file,index)=><div key={`${file.name}-${index}`} draggable={tool.multipleInputSupport&&!busy} onDragStart={event=>event.dataTransfer.setData('text/plain',String(index))} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();if(busy)return;const from=Number(event.dataTransfer.getData('text/plain'));if(!Number.isInteger(from)||from<0||from>=files.length)return;setFiles(values=>{const next=[...values];const [moved]=next.splice(from,1);next.splice(index,0,moved);return next;});}}><span>{file.name} · {(file.size/1024).toFixed(1)} KB</span>{tool.multipleInputSupport&&<><button disabled={busy||index===0} aria-label={t('前移文件','Move file earlier')} onClick={()=>setFiles(values=>{const copy=[...values];[copy[index-1],copy[index]]=[copy[index],copy[index-1]];return copy;})}>↑</button><button disabled={busy||index===files.length-1} aria-label={t('后移文件','Move file later')} onClick={()=>setFiles(values=>{const copy=[...values];[copy[index+1],copy[index]]=[copy[index],copy[index+1]];return copy;})}>↓</button></>}<button aria-label={t('移除','Remove')} disabled={busy} onClick={()=>setFiles(values=>values.filter((_,at)=>at!==index))}><X size={16}/></button></div>)}</div>
 {files.length>1&&<label>{t('预览文件','Preview file')}<select value={Math.min(activeFile,files.length-1)} onChange={event=>setActiveFile(Number(event.target.value))}>{files.map((file,i)=><option key={i} value={i}>{i+1}. {file.name}</option>)}</select></label>}
 {descriptor&&tool.category!=='data'&&<p className="file-info">{descriptor.detectedType.toUpperCase()} {descriptor.width&&<> · {descriptor.width} × {descriptor.height} px</>}{descriptor.errorCode==='ANIMATED_IMAGE_UNSUPPORTED'&&<> · {t('此工具不支持动画输入，请选择静态图片。','This tool requires a static image.')}</>}{descriptor.error&&<> · {toolError(descriptor.error,language)}</>}</p>}
 {tool.id==='file.rename'&&files.length>0&&<RenamePreview files={files} settings={settings} language={language}/>}
 {['archive.inspect','archive.zip-extract'].includes(tool.id)&&previewFile&&<ArchiveInspector file={previewFile} language={language}/>}
 {tool.id==='image.crop'&&previewFile&&!!descriptor?.width&&(descriptor?.width??0)*(descriptor?.height??0)<=21_000_000&&previewFile.size<=25*1024*1024&&<fieldset disabled={busy}><CropEditor key={previewFile.name+previewFile.lastModified} file={previewFile} onChange={update} language={language}/></fieldset>}
 {tool.category==='image'&&tool.id!=='image.crop'&&previewFile&&['jpg','png','webp','gif'].includes(descriptor?.detectedType??'')&&(descriptor?.width??0)*(descriptor?.height??0)<=24_000_000&&<><OriginalImage file={previewFile} tool={tool.id} settings={settings} onInfo={(width,height)=>setSizes(old=>old.width===width&&old.height===height?old:{width,height})}/>{tool.id==='image.resize'&&<p>{t('预计输出','Expected output')}: {expectedWidth} × {expectedHeight} px</p>}</>}
 {tool.id==='image.crop'&&previewFile&&((descriptor?.width??0)*(descriptor?.height??0)>21_000_000||previewFile.size>25*1024*1024)&&<p role="alert">{t('裁剪预览限制为 21 百万像素、25 MB，请先缩小图片。','Crop preview accepts up to 21 megapixels and 25 MB. Resize the image first.')}</p>}
 {tool.id==='image.favicon'&&previewFile&&!!descriptor?.width&&(descriptor?.width??0)*(descriptor?.height??0)<=24_000_000&&<FaviconPreview file={previewFile} fit={settings.fit} language={language}/>}
 {['pdf.organize','pdf.extract-pages','pdf.delete-pages','pdf.rotate'].includes(tool.id)&&previewFile&&<PdfOrganizer file={previewFile} onChange={update} language={language} mode={tool.id} settings={settings} disabled={busy}/>}
 {tool.category==='pdf'&&previewFile&&!['pdf.organize','pdf.extract-pages','pdf.delete-pages','pdf.rotate','pdf.unlock'].includes(tool.id)&&<PdfPreview key={previewFile.name+previewFile.lastModified} file={previewFile} settings={settings} onChange={update} language={language} disabled={busy} toolId={tool.id}/>}
 {(tool.category==='audio'||tool.category==='video')&&tool.id!=='audio.merge'&&previewFile&&<MediaEditor file={previewFile} toolId={tool.id} settings={settings} onChange={update} language={language} disabled={busy}/>}
 {tool.id==='audio.merge'&&files.length>0&&<><MergeAudioPreview files={files} durations={durations} language={language}/><p>{t('拼接总时长','Combined duration')} {Object.values(durations).reduce((n,value)=>n+value,0).toFixed(2)} s</p><div className="merge-timeline">{files.map((file,index)=><div key={index}><strong>{index+1}. {file.name}</strong><PlaylistItem file={file} onDuration={duration=>setDurations(old=>old[file.name]===duration?old:{...old,[file.name]:duration})}/></div>)}</div></>}
 </section><section className="tool-control-panel"><fieldset disabled={busy} className="tool-settings">{schema.map(field=><label key={field.key}>{field.label[language]}{field.kind==='select'?<select aria-label={field.label[language]} value={String(settings[field.key]??'')} onChange={event=>update({[field.key]:event.target.value})}>{(tool.id==='document.convert'&&files[0]?.name.toLowerCase().endsWith('.pdf')&&field.key==='output'?[{value:'pdf',label:{zh:'DOCX（文字提取）',en:'DOCX (text extraction)'}}]:field.options)?.filter(option=>{if(field.key!=='output'||!capabilities||option.value==='preserve')return true;if(tool.workspace){if(tool.category==='image'&&['png','jpg','webp'].includes(option.value))return true;const source=descriptor?.detectedType??(tool.category==='pdf'?'pdf':tool.category==='audio'?'wav':tool.category==='video'?'mp4':null);return !source||tool.id==='document.convert'&&source==='pdf'||capabilities.server.some(item=>item.input===source&&item.outputs.includes(option.value));}return capabilities.tools?.[tool.id]?.outputs.includes(option.value)??true;}).map(option=><option key={option.value} value={option.value}>{['0','1','6'].includes(option.value)&&tool.id==='archive.zip-create'?({0:t('仅打包','Store'),1:t('快速压缩','Fast'),6:t('标准压缩','Standard')} as Record<string,string>)[option.value]:option.label[language]}</option>)}</select>:<input aria-label={field.label[language]} type={field.kind==='boolean'?'checkbox':field.kind==='number'?'number':field.key==='password'||field.key==='confirm_password'?'password':'text'} autoComplete="off" step={field.kind==='number'?'any':undefined} min={field.min} max={field.max} checked={field.kind==='boolean'?Boolean(settings[field.key]):undefined} value={field.kind==='boolean'?undefined:String(settings[field.key]??'')} onChange={event=>{if(field.key==='position')update({x_percent:undefined,y_percent:undefined});update({[field.key]:field.kind==='boolean'?event.target.checked:field.kind==='number'?Number(event.target.value):event.target.value});}}/>}</label>)}</fieldset>
 {['image.rotate','image.flip'].includes(tool.id)&&<button disabled={busy} onClick={()=>update(tool.id==='image.rotate'?{rotation:0}:{direction:'none'})}>{t('恢复原图','Reset image')}</button>}{['image.rotate','image.flip'].includes(tool.id)&&<button disabled={busy||!transformUndo.length} onClick={()=>{const previous=transformUndo[transformUndo.length-1];setSettings(old=>({...old,...previous}));setTransformUndo(old=>old.slice(0,-1));}}>{t('撤销','Undo')}</button>}
 {tool.id==='file.hash'&&settings.algorithm!=='sha256'&&<p>{t('MD5 和 SHA-1 适合比对文件，不适合安全验证。','MD5 and SHA-1 can compare files; use SHA-256 for security checks.')}</p>}
 {tool.id==='video.compress'&&<p>{settings.keep_resolution!==false?t('保留原分辨率，重新编码。','Keeps source dimensions and re-encodes.'):t('轻度最高 1080p，均衡 720p，强力 480p。','Light: up to 1080p; balanced: 720p; strong: 480p.')}</p>}
 {tool.id==='pdf.split'&&<p>{t('用分号分组，例如 1-3;4-6；all 按每页拆分。','Separate groups with semicolons, e.g. 1-3;4-6. all creates one file per page.')}</p>}
 {tool.id==='image.strip-metadata'&&<p>{t('移除拍摄、位置和文字信息。保留色彩配置可减少颜色变化。','Removes camera, location and text tags. Keeping the color profile helps preserve colors.')}</p>}
 {tool.processing==='server'&&capabilities&&!toolAvailable(tool,capabilities)&&<p role="alert">{t('当前服务未启用此工具所需的转换组件。','This server lacks the required converter.')}</p>}
 <div className="tool-result-actions"><button hidden={tool.id==='archive.inspect'} className="primary-button" disabled={busy||(!files.length&&tool.category!=='data')||(tool.processing==='server'&&!!capabilities&&!toolAvailable(tool,capabilities))} onClick={()=>void run()}>{busy?stageNames[stage]??t('处理中','Processing'):action}</button>{busy&&<button onClick={()=>void cancel()}>{t('取消处理','Cancel processing')}</button>}</div>{busy&&<progress value={progress} max="1"/>}{error&&<p role="alert">{error}</p>}
 {schema.length>0&&!['pdf.protect','pdf.unlock'].includes(tool.id)&&<details className="preset-details"><summary>{t('预设','Presets')}</summary><fieldset disabled={busy} className="tool-settings"><label>{t('选择预设','Choose preset')}<select defaultValue="" onChange={event=>{const preset=presets.find(value=>value.id===event.target.value);if(preset)update(preset.settings);}}><option value="">—</option>{presets.filter(preset=>preset.toolId===tool.id).map(preset=><option key={preset.id} value={preset.id}>{preset.name}</option>)}</select></label><label>{t('预设名称','Preset name')}<input maxLength={50} value={presetName} onChange={event=>setPresetName(event.target.value)}/></label><button disabled={!presetName.trim()} onClick={()=>{setPresets(storeToolPreset(tool.id,presetName,settings));setPresetName('');}}>{t('保存','Save')}</button></fieldset></details>}
 {stale&&<p className="result-stale">{t('输入或设置已更改，下面保留上次结果。','Inputs or settings changed. The previous result remains below.')}</p>}{result&&<ResultPanel key={snapshot+result.kind} result={result} language={language} original={resultInputs} settings={snapshot?JSON.parse(snapshot)[1]:settings} toolId={tool.id} onRetry={names=>void run(names)}/>}
 </section></div></main></WorkbenchShell>;
}
